### ISSUE TITLE
logger-0.3 no longer builds

### ISSUE THREAD

**Issue by vegai** [iron/logger#74]
```
/Users/vesakaihlavirta/.multirust/toolchains/stable/cargo/registry/src/github.com-0a35038f75765ae4/logger-0.0.3/src/lib.rs:80:57: 80:75 note: in this expansion of try! (defined in <std macros>)
<std macros>:6:1: 6:32 help: run `rustc --explain E0277` to see a detailed explanation
<std macros>:6:1: 6:32 note: required by `core::convert::From::from`
<std macros>:6:1: 6:32 error: the trait `core::convert::From<term::Error>` is not implemented for the type `std::io::error::Error` [E0277]
<std macros>:6 $ crate:: convert:: From:: from ( err ) ) } } )
```

I suppose https://github.com/iron/logger/pull/72 could be related

**Comment by vegai** [comment]
Ah, correction. The above happens with beta and nightly as well.

**Comment by ozten** [comment]
This is actually fixed on master, but not published to crates.io.
To unblock myself, I'm using master directly:

    [dependencies]
    logger = { git = "https://github.com/iron/logger" }

If you'd like to use an [un-merged fix for a different issue](https://github.com/iron/logger/pull/72), you can also point to a branch:

    [dependencies]
    logger = { git = "https://github.com/mcasper/logger", branch = "bug/update_term" }

**Comment by untitaker** [comment]
Meanwhile a new version was released.
