### ISSUE TITLE
Windows: All requests fail with default format: NotSupported

### ISSUE THREAD

**Issue by msiemens** [iron/logger#79]
When using the logging middleware, all requests fail with the following log messages:

```
2016-03-28T21:44:08+07:00 ERROR iron::iron - Error handling:
Request {
    url: Url { scheme: "http", host: Domain("localhost"), port: 3000, path: ["12345"], username: None, password: None, query: None, fragment: None }
    method: Get
    remote_addr: V6([::1]:59540)
    local_addr: V6([::1]:3000)
}
Error was: Error { repr: Custom(Custom { kind: Other, error: NotSupported }) }
```

The `NotSupported` seems to come from [term](https://github.com/Stebalien/term/blob/88159b0bd5a824e8eaa14e1c270f4ecfc09d3a1a/src/lib.rs#L184) indicating that the used terminal doesn't support the requested term capabilities.

The relevant source code used:

``` rust
let mut chain = Chain::new(router);

let (logger_before, logger_after) = Logger::new(None);
chain.link_before(logger_before);
chain.link_after(logger_after);
```

Chaning the format string to not use colors solves the problem.

Rust: rustc 1.9.0-nightly (d5a91e695 2016-03-26)
Iron: 0.3.0
Logger: 0.0.3
OS: Windows 7 SP 1
Shell: zsh
Env: msys2
I also used ConEmu, if that's relevant.

**Comment by jwilm** [comment]
Ran into this as well. Thanks @msiemens for figuring out the problem.

**Comment by tomprince** [comment]
This looks like it no longer relevant, since this logs via the `log` crate.

**Comment by tomprince** [comment]
This looks like it no longer relevant, since this logs via the `log` crate.
