### ISSUE TITLE
Cut new breaking version

### ISSUE THREAD

**Issue by Hoverbear** [iron/logger#92]
We need to cut `0.2.0`. This is a breaking change because of #92.

**Comment by Hoverbear** [comment]
Prior to this we should handle https://github.com/iron/logger/pull/91#issuecomment-254427533

**Comment by Fiedzia** [comment]
Is there anything else to do before we can get it out?

**Comment by Hoverbear** [comment]
Reminding me 👍

**Comment by Hoverbear** [comment]
Published :)

**Comment by tomprince** [comment]
I guess this can be closed now?
