### ISSUE TITLE
Usage info

### ISSUE THREAD

**Issue by Fiedzia** [iron/logger#93]
With the switch to log crate, we need to update README (and maybe some other places) to inform users on how to set it up.

**Comment by Fiedzia** [comment]
I've opened  [94](https://github.com/iron/logger/pull/94) as a starting point. I am not quiet happy with the state of rust logging documentation, which does not cover crates that implement it, makin whole subject rather confusing for new users.

**Comment by Hoverbear** [comment]
Thanks! I like the direction there so lets move the conversation there. :)

**Comment by Fiedzia** [comment]
By "there or here" i meant "in iron-logger readme/documentation" or "in rust log crate documentation".

**Comment by jmatraszek** [comment]
I happened to struggle today with configuring logger to actually log anything and felt quite blind-folded. It worked in the end without the docs, but this will be helpful for a lot of people, for sure. Thanks!

**Comment by Hoverbear** [comment]
@jmatraszek Does [this](https://github.com/rust-lang-nursery/log#in-executables) help you get started?

**Comment by jmatraszek** [comment]
@Hoverbear Yes! Thanks.
